spring.application.name=savepass
spring.datasource.url=jdbc:mysql://localhost:3306/savepass
spring.datasource.username=root
spring.datasource.password=@Anh3112005

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=123456789